### PR TITLE
Update sidebar icons and message list layout

### PR DESCRIPTION
**Pull request by tpai**
Hi @kallepersson 

This PR is for #8 #9 #10 #11 .

Updated icons:

- Inbox
- Snoozed
- Sent
- Drafts
- Trash
- Category
- All Mail
- Spam

It will look like:

### CODE REVIEW

**Comment by kallepersson** [comment]
Thanks @tpai! I will review in the next few days and get back to you!

**Comment by kallepersson** [comment]
CSS changes look great, merging. Thanks for your contribution!

**Comment by kallepersson** [comment]
@tpai I found a small issue for smaller screens, will adapt before releasing a new version!

**Comment by tpai** [comment]
@kallepersson Could you add me as collaborator that I could directly create branch on this repo?

**Comment by kallepersson** [comment]
@tpai Let me figure out how to set up an organization first, then I can add you as a contributor. Hope that's ok!

By the way, this and your other PR has now been merged and packaged for an update. I made a small change in 6cb8d93d6ce247c6ad7344d78e4951970f84fb82 restoring starred etc for users that might still rely on them.

**Pull request merged**
